# Generated by Django 4.1.3 on 2023-03-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='stud_class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_class_name', to='facerecognition.studclass', unique=True),
        ),
    ]
