# Generated by Django 4.1.3 on 2023-03-04 17:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_timetable_stud_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='mondays',
        ),
        migrations.AddField(
            model_name='timetable',
            name='friday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=5),
        ),
        migrations.AddField(
            model_name='timetable',
            name='monday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=5),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thursday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=5),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tuesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=5),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wednesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=5),
        ),
    ]
