# Generated by Django 4.1.3 on 2023-03-06 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0003_remove_timetable_mondays_timetable_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studclass',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 3, 6), null=True),
        ),
    ]
