# Generated by Django 4.1.3 on 2023-03-07 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0004_studclass_is_lab_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 3, 7), null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('subject1_att', models.BooleanField(default=False)),
                ('subject2_att', models.BooleanField(default=False)),
                ('subject3_att', models.BooleanField(default=False)),
                ('subject4_att', models.BooleanField(default=False)),
                ('subject5_att', models.BooleanField(default=False)),
                ('stud_class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_class_name', to='facerecognition.studclass')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='facerecognition.student')),
            ],
        ),
    ]
