# Generated by Django 4.1.3 on 2023-03-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0005_alter_student_dob_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
    ]
