# Generated by Django 4.1.3 on 2022-12-25 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0006_alter_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_photo_b64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 12, 25), null=True),
        ),
    ]
