# Generated by Django 4.1.3 on 2023-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0007_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='register_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
