# Generated by Django 4.1.3 on 2023-03-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0009_academicbatch_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbatch',
            name='batch_name',
            field=models.CharField(max_length=30),
        ),
    ]
